from_latest_tag = false
ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = []
post_bump_hooks = ["git push origin","git push origin {{version}}"]
pre_package_bump_hooks = ["echo \"{{version}}\" > ./release.version"]

[commit_types]

[changelog]
template = "monorepo_remote"
package_template = "package_remote"
remote = "github.com"
repository = "cloud-backup-container"
owner = "witcom-gmbh"
authors = [
    { signature = "Carsten Buchberger", username = "iceman91176" },
]


[bump_profiles]

[packages]
postgres-cloud-backup = { path = "postgres-cloud-backup", public_api = false,post_bump_hooks = ["git push origin", "git push origin postgres-cloud-backup-{{version}}"] }
postgres-cloud-restore = { path = "postgres-cloud-restore", public_api = false,post_bump_hooks = ["git push origin","git push origin postgres-cloud-restore-{{version}}"] }
mysql-cloud-backup = { path = "mysql-cloud-backup", public_api = false,post_bump_hooks = ["git push origin","git push origin mysql-cloud-backup-{{version}}"] }
mysql-cloud-restore = { path = "mysql-cloud-restore", public_api = false,post_bump_hooks = ["git push origin","git push origin mysql-cloud-restore-{{version}}"] }
